apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  externalIPs:
  - 192.168.0.15
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
  type: NodePort

